use_frameworks!

platform :ios, '8.0'

target 'ZJScrollViewModule_Example' do
  pod 'ZJScrollViewModule', :path => '../'

  target 'ZJScrollViewModule_Tests' do
    inherit! :search_paths

    
  end
end
